"""
services/response_cache.py
---------------------------
ITEM PASS 5 (Part 1, items 20-23: "backend dashboard queries must be
checked for unnecessary repeated queries", "do not calculate the same
large dataset repeatedly for every dashboard component if it can safely
be reused"): dashboard_kpis.compute_home_dashboard() and its sibling tab
functions are documented (see dashboard.py's home_dashboard docstring) as
computing directly from SapInvoiceFact/LandmarkVisitFact on EVERY request
- correct, but expensive, and the exact same (filters, data) pair gets
recomputed from scratch every time: every user who opens Dashboard with
the default (no filter) view recomputes the identical aggregation, and
the dashboard-refresh-interval / explicit Refresh button (already
implemented) re-hits it repeatedly too.

This is a small in-process response cache for exactly that case, built to
be IMPOSSIBLE to serve stale data after an import - rather than a blind
time-based TTL (which could serve a pre-import snapshot for however long
the TTL window is), the cache key includes the actual data version:
`MAX(imported_at)` across the two source fact tables. The moment an
import lands new rows, that MAX changes, the cache key changes, and the
next request recomputes for real - old entries are simply never looked
up again (and are pruned opportunistically, see _prune below) rather than
needing an explicit "invalidate on import" call site to remember to add
wherever an import could happen.

Deliberately NOT a second source of truth: this holds only the already-
computed RESPONSE for a given (endpoint, filters, data-version) tuple,
generated by asking the database for that exact same computation the
first time - it can never diverge from what a fresh, uncached call would
return for that same data version.

Explicitly NOT used for anything mutating, sensitive, or per-user (see
call sites in dashboard.py: only the six read-only tab endpoints that
compute from the shared company-wide fact tables).
"""
import time
import threading
from typing import Callable

from sqlalchemy import func
from sqlalchemy.orm import Session

from app.models.analytics_facts import SapInvoiceFact, LandmarkVisitFact

_lock = threading.Lock()
_cache: dict[tuple, tuple[float, dict]] = {}  # key -> (stored_at, value)
_MAX_ENTRIES = 200  # small in-process cache; this is a handful of distinct filter combos, not a general-purpose store
_MAX_AGE_SECONDS = 900  # belt-and-suspenders absolute ceiling (15 min) even though the data-version key already invalidates on import - guards against a clock/version edge case rather than being the primary invalidation mechanism


def _data_version(db: Session) -> str:
    """
    A cheap, correctness-critical read: the latest `imported_at` across
    both fact tables this dashboard reads from. Two separate MAX()
    queries against already-indexed/tiny-to-scan datetime columns - not
    the expensive aggregation this cache exists to avoid repeating, just
    a freshness fingerprint for it.
    """
    a = db.query(func.max(SapInvoiceFact.imported_at)).scalar()
    b = db.query(func.max(LandmarkVisitFact.imported_at)).scalar()
    return f"{a.isoformat() if a else ''}|{b.isoformat() if b else ''}"


def _prune() -> None:
    if len(_cache) <= _MAX_ENTRIES:
        return
    now = time.time()
    stale = [k for k, (stored_at, _) in _cache.items() if now - stored_at > _MAX_AGE_SECONDS]
    for k in stale:
        _cache.pop(k, None)
    if len(_cache) > _MAX_ENTRIES:
        # still oversized after pruning by age - drop oldest entries first
        for k, _ in sorted(_cache.items(), key=lambda kv: kv[1][0])[: len(_cache) - _MAX_ENTRIES]:
            _cache.pop(k, None)


def cached_dashboard_call(db: Session, endpoint: str, params: dict, compute: Callable[[], dict]) -> dict:
    """
    Looks up (endpoint, sorted params, current data version) in the
    cache; on a miss, calls `compute()` (the real, correct, already-
    working aggregation - unchanged), stores the result, and returns it.
    On a hit, returns the stored result without touching
    SapInvoiceFact/LandmarkVisitFact at all beyond the two cheap MAX()
    freshness queries above.
    """
    version = _data_version(db)
    key = (endpoint, tuple(sorted(params.items())), version)
    with _lock:
        hit = _cache.get(key)
        if hit is not None and time.time() - hit[0] <= _MAX_AGE_SECONDS:
            return hit[1]
    # Miss (or expired-by-absolute-ceiling): compute for real, outside
    # the lock - this is the same expensive call an uncached request
    # would make, we're just choosing not to repeat it for identical
    # (endpoint, filters, data-version) requests.
    result = compute()
    with _lock:
        _cache[key] = (time.time(), result)
        _prune()
    return result
