import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const TABLES=['drivers','helpers','vehicles','areas','vacations','route_assignments','experience_history','customer_aliases','consumer_salesmen','driver_aliases','driver_daily_divisions','sap_invoice_facts','landmark_visit_facts','import_batches','raw_import_rows','learned_values','dashboard_config_rules','appearance_config','feature_flags','control_center_config','route_sheet_layout','app_backups','audit_log','jobs','correlation_results','identity_review_items','price_change_campaigns','price_change_items','price_change_assignments','price_change_assignment_items','price_change_customer_visits','price_change_visit_items','price_change_campaign_areas','price_change_default_areas','bulk_organizer_plans','bulk_organizer_month_defaults','department_portal_accounts','department_portal_sessions','department_portal_submissions','department_dispatch_entries'];
const PRIMARY=new Set(['drivers','helpers','vehicles','areas','vacations','route_assignments','experience_history','customer_aliases','consumer_salesmen','driver_aliases','driver_daily_divisions','sap_invoice_facts','landmark_visit_facts','import_batches','raw_import_rows','learned_values','dashboard_config_rules','appearance_config','feature_flags','control_center_config','route_sheet_layout','app_backups','audit_log','jobs','correlation_results','identity_review_items']);
const SECONDARY=new Set(['price_change_campaigns','price_change_items','price_change_assignments','price_change_assignment_items','price_change_customer_visits','price_change_visit_items','price_change_campaign_areas','price_change_default_areas']);
const TERTIARY=new Set(['bulk_organizer_plans','bulk_organizer_month_defaults','department_portal_accounts','department_portal_sessions','department_portal_submissions','department_dispatch_entries']);
function json(x:any,status=200){return new Response(JSON.stringify(x),{status,headers:cors})}
function db(project?:string){const k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const p=createClient(Deno.env.get('SUPABASE_URL')!,k.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});if(project==='secondary'||(!PRIMARY.has('')&&false))return createClient('https://vyqyrcqrdsyrxywglqbh.supabase.co','sb_publishable_CreQOVJ9ZYkp6PGBqWHlVA_q1CSur1n',{auth:{persistSession:false}});if(project==='tertiary')return createClient('https://ptmbtveernkglmubrtdw.supabase.co','sb_publishable_dX0pnn8--xI_WJtqweaWGA_8yh8ec5U',{auth:{persistSession:false}});return p}
function clientFor(table:string,project?:string){if(project==='secondary'||SECONDARY.has(table))return db('secondary');if(project==='tertiary'||TERTIARY.has(table))return db('tertiary');return db('primary')}
function safeTable(t:string){return TABLES.includes(t)} function safeCol(c:string){return /^[A-Za-z_][A-Za-z0-9_]*$/.test(c)}
function applyFilters(q:any,fs:any[]){for(const f of(Array.isArray(fs)?fs.slice(0,30):[])){if(!f||!safeCol(String(f.column)))continue;const v=f.value,o=String(f.op||'eq');if(o==='eq')q=q.eq(f.column,v);else if(o==='neq')q=q.neq(f.column,v);else if(o==='ilike')q=q.ilike(f.column,'%'+String(v)+'%');else if(o==='gte')q=q.gte(f.column,v);else if(o==='lte')q=q.lte(f.column,v);else if(o==='gt')q=q.gt(f.column,v);else if(o==='lt')q=q.lt(f.column,v);else if(o==='in'&&Array.isArray(v))q=q.in(f.column,v.slice(0,200));}return q}
function normalize(a:any){const x={...a};if(x.table==='driver_daily_divisions'){if(typeof x.select==='string'&&x.select!=='*')x.select=x.select.replace(/\bdriver_id\b/g,'person_code as driver_id');if(Array.isArray(x.filters))x.filters=x.filters.map((f:any)=>f&&f.column==='driver_id'?{...f,column:'person_code'}:f);if(x.order_by==='driver_id')x.order_by='person_code'}return x}
async function readTable(a:any){const x=normalize(a);if(!safeTable(x.table))throw Error('Table is not available to LOGI.');let q=clientFor(x.table,x.project).from(x.table).select(typeof x.select==='string'?x.select:'*');q=applyFilters(q,x.filters);if(x.order_by&&safeCol(String(x.order_by)))q=q.order(x.order_by,{ascending:x.ascending!==false});const r=await q.limit(Math.min(Math.max(Number(x.limit||100),1),500));if(r.error)throw Error(r.error.message);return r.data||[]}
async function bestDriver(){const d=db('primary');const r=await d.from('route_assignments').select('driver_code,driver_name,driver_score').not('driver_code','is',null).not('driver_score','is',null).limit(500);if(r.error)throw Error(r.error.message);if((r.data||[]).length){const m=new Map();for(const x of r.data||[]){const k=String(x.driver_code||x.driver_name||'').trim();if(!k)continue;const v=m.get(k)||{driver_code:x.driver_code||'',driver_name:x.driver_name||'',scores:[]};v.scores.push(Number(x.driver_score)||0);if(x.driver_name)v.driver_name=x.driver_name;m.set(k,v)}const out=[...m.values()].map(v=>({...v,avg_score:v.scores.reduce((a,b)=>a+b,0)/v.scores.length,assignments:v.scores.length})).sort((a,b)=>b.avg_score-a.avg_score);if(out[0])return{type:'route_score',...out[0]}}
const s=await d.from('sap_invoice_facts').select('driver_code,driver_name').not('driver_code','is',null).limit(50000);if(s.error)throw Error(s.error.message);const m=new Map();for(const x of s.data||[]){const k=String(x.driver_code||'').trim();if(!k)continue;const v=m.get(k)||{driver_code:k,driver_name:x.driver_name||'',invoices:0};v.invoices++;if(x.driver_name)v.driver_name=x.driver_name;m.set(k,v)}const out=[...m.values()].sort((a,b)=>b.invoices-a.invoices);return out[0]?{type:'invoice_volume',...out[0]}:null}
async function bestHelper(){const d=db('primary');const r=await d.from('route_assignments').select('helper_code,helper_name,helper_score').not('helper_code','is',null).not('helper_score','is',null).limit(500);if(r.error)throw Error(r.error.message);if((r.data||[]).length){const m=new Map();for(const x of r.data||[]){const k=String(x.helper_code||x.helper_name||'').trim();if(!k)continue;const v=m.get(k)||{helper_code:x.helper_code||'',helper_name:x.helper_name||'',scores:[]};v.scores.push(Number(x.helper_score)||0);if(x.helper_name)v.helper_name=x.helper_name;m.set(k,v)}const out=[...m.values()].map(v=>({...v,avg_score:v.scores.reduce((a,b)=>a+b,0)/v.scores.length,assignments:v.scores.length})).sort((a,b)=>b.avg_score-a.avg_score);if(out[0])return{type:'route_score',...out[0]}}const s=await d.from('sap_invoice_facts').select('helper_code,helper_name').not('helper_code','is',null).limit(50000);if(s.error)throw Error(s.error.message);const m=new Map();for(const x of s.data||[]){const k=String(x.helper_code||'').trim();if(!k)continue;const v=m.get(k)||{helper_code:k,helper_name:x.helper_name||'',invoices:0};v.invoices++;if(x.helper_name)v.helper_name=x.helper_name;m.set(k,v)}const out=[...m.values()].sort((a,b)=>b.invoices-a.invoices);return out[0]?{type:'invoice_volume',...out[0]}:null}
async function summarize(a:any){const d=clientFor(a.table,a.project);const h=await applyFilters(d.from(a.table).select('*',{head:true,count:'exact'}),a.filters);if(h.error)throw Error(h.error.message);const out:any={count:h.count||0};if(!a.column)return out;const vals:any[]=[];for(let from=0;from<50000;from+=1000){const r=await applyFilters(d.from(a.table).select(a.column),a.filters).range(from,from+999);if(r.error)throw Error(r.error.message);vals.push(...(r.data||[]).map((x:any)=>x[a.column]).filter((x:any)=>x!==null&&x!==undefined&&x!==''));if((r.data||[]).length<1000)break}const nums=vals.map(Number).filter(Number.isFinite);out.distinct_count=new Set(vals.map(String)).size;if(nums.length){out.sum=nums.reduce((a,b)=>a+b,0);out.avg=out.sum/nums.length;out.min=Math.min(...nums);out.max=Math.max(...nums)}return out}
function cleanProviderReply(text:string){
  let s=String(text||'').trim();
  // Remove model planning/retrieval narration before the actual answer.
  const wait=/Please hold on|Please wait|hold on|wait a moment|give me a moment|\[Retrieving data\]|\[Checking data\]|\[Loading data\]/i;
  if(wait.test(s)){
    const marker=s.search(wait);
    if(marker>=0){
      const after=s.slice(marker).replace(/^.*?(?:\]|\.)?\s*/s,'').trim();
      if(after) s=after;
    }
  }
  s=s.replace(/^(?:while I retrieve[^.]*\.?|while I check[^.]*\.?|I(?:'|’)ll retrieve[^.]*\.?|I will retrieve[^.]*\.?|I(?:'|’)ll check[^.]*\.?|I will check[^.]*\.?|To identify[^.]*\.?|To determine[^.]*\.?|Let me check[^.]*\.?|Let me look[^.]*\.?|I(?:'|’)ll first[^.]*\.?|I will first[^.]*\.?)[\s\S]*?(?=(?:Based on|The best|The top|There are|I found|[A-Za-z][^\n]{0,80} is ))/i,'');
  s=s.replace(/^(?:\[Retrieving data\]|\[Checking data\]|\[Loading data\])\s*/i,'').trim();
  s=s.replace(/(?:\n|\s)+(?:Please hold on|Please wait|hold on|wait a moment|give me a moment)\.?[\s\S]*$/i,'').trim();
  return s||'I could not find a direct answer in the available live data.';
}

async function providerCall(provider:string,key:string,model:string,messages:any[]){const base=provider==='groq'?'https://api.groq.com/openai/v1':provider==='openrouter'?'https://openrouter.ai/api/v1':'https://api.openai.com/v1';const r=await fetch(base+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model:model||'gpt-4o-mini',messages,temperature:.15})});const b=await r.json();if(!r.ok)throw Error(b?.error?.message||'Provider HTTP '+r.status);return b?.choices?.[0]?.message?.content||''}
async function discoverSchemas(){const groups=[['primary',PRIMARY],['secondary',SECONDARY],['tertiary',TERTIARY]];const out:any[]=[];for(const g of groups){const project=g[0] as string;const set=g[1] as Set<string>;const rows=await Promise.all([...set].map(async(table:string)=>{try{const r=await db(project).from(table).select('*').limit(1);return {project,table,columns:r.error?[]:Object.keys((r.data||[])[0]||{})};}catch(e:any){return {project,table,columns:[]};}}));out.push(...rows);}return out;}
function parsePlanner(text:string){const t=String(text||'').replace(/\x60/g,'').trim();const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<a)throw Error('Invalid planner response');return JSON.parse(t.slice(a,b+1));}
async function runPlan(plan:any){const out:any[]=[];for(const a of(Array.isArray(plan?.actions)?plan.actions.slice(0,12):[])){try{if(a.action==='summarize')out.push({action:a,summary:await summarize(a)});else if(a.action==='read')out.push({action:a,rows:await readTable(a)});}catch(e:any){out.push({action:a,error:e?.message||'query failed'});}}return out;}
async function main(req:Request){if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const body=await req.json();const d=db('primary');const msg=String(body.message||'').trim();if(!msg)return json({reply:'Tell me what you want me to do.'});if(/\b(best|top)\b.*\bdriver\b|\bdriver\b.*\b(best|top)\b/i.test(msg)){try{const b=await bestDriver();if(b){const reply=b.type==='route_score'?'Based on route-assignment driver_score, the top driver is '+(b.driver_name||b.driver_code)+' ('+(b.driver_code||'no code')+') with an average score of '+b.avg_score.toFixed(2)+' across '+b.assignments+' assignment(s). This is not a stored performance_rating.':'There are no route-assignment scores in the live data, so I used SAP invoice volume instead. '+(b.driver_name||b.driver_code)+' ('+(b.driver_code||'no code')+') has the highest recorded invoice volume with '+b.invoices+' invoice record(s). This measures workload/volume, not quality.';return json({reply,provider_used:'live-data',fallback_used:false,rag_available:true,pending_action:null})}}catch(e:any){return json({reply:'LOGI hit a live data error: '+(e?.message||'Unknown error'),provider_used:'live-data',fallback_used:false},400)}}
if(/\b(best|top)\b.*\bhelper\b|\bhelper\b.*\b(best|top)\b/i.test(msg)){try{const b=await bestHelper();if(b){const reply=b.type==='route_score'?'Based on route-assignment helper_score, the top helper is '+(b.helper_name||b.helper_code)+' ('+(b.helper_code||'no code')+') with an average score of '+b.avg_score.toFixed(2)+' across '+b.assignments+' assignment(s). This is not a stored performance_rating.':'There are no route-assignment helper scores in the live data, so I used SAP invoice volume instead. '+(b.helper_name||b.helper_code)+' ('+(b.helper_code||'no code')+') has the highest recorded invoice volume with '+b.invoices+' invoice record(s). This measures workload/volume, not quality.';return json({reply,provider_used:'live-data',fallback_used:false,rag_available:true,pending_action:null})}}catch(e:any){return json({reply:'LOGI hit a live data error: '+(e?.message||'Unknown error'),provider_used:'live-data',fallback_used:false},400)}}
const cfg=(await d.from('ai_provider_config').select('provider,model,api_key,fallback_enabled,fallback_chain').eq('id','00000000-0000-0000-0000-000000000001').maybeSingle()).data||{};
if(cfg.api_key){const chain=[{provider:cfg.provider,model:cfg.model,api_key:cfg.api_key},...(cfg.fallback_enabled&&Array.isArray(cfg.fallback_chain)?cfg.fallback_chain:[])].filter((x:any)=>x.provider&&x.api_key);const callChain=async(messages:any[])=>{let err='Unknown provider error';for(let i=0;i<chain.length;i++){try{return {text:await providerCall(chain[i].provider,chain[i].api_key,chain[i].model,messages),provider:chain[i].provider,fallback:i>0};}catch(e:any){err=e?.message||err;}}throw Error(err);};const schemas=await discoverSchemas();const planner='You are LOGI, a live DispatchOPS analyst. Decide what live data is needed. Return ONLY JSON with needs_data, actions, answer_focus. Each action must use only tables and columns in SCHEMA and can read or summarize. Use multiple databases when needed. Never narrate work or ask to wait. SCHEMA:'+JSON.stringify(schemas);let plan:any;try{plan=parsePlanner((await callChain([{role:'system',content:planner},{role:'user',content:msg}])).text);}catch(e:any){return json({reply:'I could not analyze the live data request: '+(e?.message||'Unknown error'),provider_used:cfg.provider,fallback_used:false,rag_available:true,pending_action:null});}const results=plan.needs_data?await runPlan(plan):[];const finalPrompt='Answer the user directly. Use only supplied live results for factual program data. Combine Primary, Secondary, and Tertiary when relevant. Never mention querying, tools, providers, retrieval, planning, or waiting. Never invent facts. User: '+msg+'\nFocus: '+String(plan.answer_focus||'')+'\nResults: '+JSON.stringify(results);try{const ai=await callChain([{role:'system',content:'You are LOGI. Give the final useful answer immediately.'},{role:'user',content:finalPrompt}]);return json({reply:cleanProviderReply(ai.text),provider_used:ai.provider,fallback_used:ai.fallback,rag_available:true,pending_action:null});}catch(e:any){return json({reply:'LOGI could not get the AI answer: '+(e?.message||'Unknown error'),provider_used:cfg.provider,fallback_used:false,rag_available:true,pending_action:null});}}
return json({reply:'LOGI is not configured with an AI provider yet.',provider_used:'live-data',fallback_used:false,rag_available:true,pending_action:null});
}
Deno.serve(main);
