import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const TABLES=['drivers','helpers','vehicles','areas','vacations','route_assignments','experience_history','customer_aliases','consumer_salesmen','driver_aliases','driver_daily_divisions','sap_invoice_facts','landmark_visit_facts','import_batches','raw_import_rows','learned_values','dashboard_config_rules','appearance_config','feature_flags','control_center_config','route_sheet_layout','app_backups','audit_log','jobs','correlation_results','identity_review_items','price_change_campaigns','price_change_items','price_change_assignments','price_change_assignment_items','price_change_customer_visits','price_change_visit_items','price_change_campaign_areas','price_change_default_areas','bulk_organizer_plans','bulk_organizer_month_defaults','department_portal_accounts','department_portal_sessions','department_portal_submissions','department_dispatch_entries'];
const PRIMARY=new Set(['drivers','helpers','vehicles','areas','vacations','route_assignments','experience_history','customer_aliases','consumer_salesmen','driver_aliases','driver_daily_divisions','sap_invoice_facts','landmark_visit_facts','import_batches','raw_import_rows','learned_values','dashboard_config_rules','appearance_config','feature_flags','control_center_config','route_sheet_layout','app_backups','audit_log','jobs','correlation_results','identity_review_items']);
const SECONDARY=new Set(['price_change_campaigns','price_change_items','price_change_assignments','price_change_assignment_items','price_change_customer_visits','price_change_visit_items','price_change_campaign_areas','price_change_default_areas']);
const TERTIARY=new Set(['bulk_organizer_plans','bulk_organizer_month_defaults','department_portal_accounts','department_portal_sessions','department_portal_submissions','department_dispatch_entries']);
function json(x:any,status=200){return new Response(JSON.stringify(x),{status,headers:cors})}
function db(project?:string){const k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const p=createClient(Deno.env.get('SUPABASE_URL')!,k.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});if(project==='secondary'||(!PRIMARY.has('')&&false))return createClient('https://vyqyrcqrdsyrxywglqbh.supabase.co','sb_publishable_CreQOVJ9ZYkp6PGBqWHlVA_q1CSur1n',{auth:{persistSession:false}});if(project==='tertiary')return createClient('https://ptmbtveernkglmubrtdw.supabase.co','sb_publishable_dX0pnn8--xI_WJtqweaWGA_8yh8ec5U',{auth:{persistSession:false}});return p}
function clientFor(table:string,project?:string){if(project==='secondary'||SECONDARY.has(table))return db('secondary');if(project==='tertiary'||TERTIARY.has(table))return db('tertiary');return db('primary')}
function safeTable(t:string){return TABLES.includes(t)} function safeCol(c:string){return /^[A-Za-z_][A-Za-z0-9_]*$/.test(c)}
function applyFilters(q:any,fs:any[]){for(const f of(Array.isArray(fs)?fs.slice(0,30):[])){if(!f||!safeCol(String(f.column)))continue;const v=f.value,o=String(f.op||'eq');if(o==='eq')q=q.eq(f.column,v);else if(o==='neq')q=q.neq(f.column,v);else if(o==='ilike')q=q.ilike(f.column,'%'+String(v)+'%');else if(o==='gte')q=q.gte(f.column,v);else if(o==='lte')q=q.lte(f.column,v);else if(o==='gt')q=q.gt(f.column,v);else if(o==='lt')q=q.lt(f.column,v);else if(o==='in'&&Array.isArray(v))q=q.in(f.column,v.slice(0,200));}return q}
function normalize(a:any){const x={...a};if(x.table==='driver_daily_divisions'){if(typeof x.select==='string'&&x.select!=='*')x.select=x.select.replace(/\bdriver_id\b/g,'person_code as driver_id');if(Array.isArray(x.filters))x.filters=x.filters.map((f:any)=>f&&f.column==='driver_id'?{...f,column:'person_code'}:f);if(x.order_by==='driver_id')x.order_by='person_code'}return x}
async function readTable(a:any){const x=normalize(a);if(!safeTable(x.table))throw Error('Table is not available to LOGI.');let q=clientFor(x.table,x.project).from(x.table).select(typeof x.select==='string'?x.select:'*');q=applyFilters(q,x.filters);if(x.order_by&&safeCol(String(x.order_by)))q=q.order(x.order_by,{ascending:x.ascending!==false});const r=await q.limit(Math.min(Math.max(Number(x.limit||100),1),500));if(r.error)throw Error(r.error.message);return r.data||[]}
async function rankedPerson(role:'driver'|'helper'){
const d=db('primary');
const codeCol=role==='driver'?'driver_code':'helper_code';
const nameCol=role==='driver'?'driver_name':'helper_name';
const scoreCol=role==='driver'?'driver_score':'helper_score';
const r=await d.from('route_assignments').select(`${codeCol},${nameCol},${scoreCol}`).not(codeCol,'is',null).not(scoreCol,'is',null).limit(5000);
if(r.error)throw Error(r.error.message);
const m=new Map<string,{code:string;name:string;scores:number[]}>();
for(const x of r.data||[]){const code=String(x[codeCol]||x[nameCol]||'').trim();if(!code)continue;const v=m.get(code)||{code,name:String(x[nameCol]||''),scores:[]};v.scores.push(Number(x[scoreCol])||0);if(x[nameCol])v.name=String(x[nameCol]);m.set(code,v)}
const out=[...m.values()].map(v=>({...v,avg_score:v.scores.reduce((a,b)=>a+b,0)/v.scores.length,assignments:v.scores.length,has_nonzero:v.scores.some(s=>s!==0)}));
const scored=out.filter(v=>v.has_nonzero).sort((a,b)=>b.avg_score-a.avg_score);
if(scored[0])return{type:'route_score',role,...scored[0]};
const byWorkload=out.sort((a,b)=>b.assignments-a.assignments);
return byWorkload[0]?{type:'assignment_volume',role,...byWorkload[0]}:null;
}
async function bestDriver(){
const b=await rankedPerson('driver');
if(b?.type==='route_score')return{type:'route_score',driver_code:b.code,driver_name:b.name,avg_score:b.avg_score,assignments:b.assignments};
const d=db('primary');const s=await d.from('sap_invoice_facts').select('driver_code,driver_name').not('driver_code','is',null).limit(50000);if(s.error)throw Error(s.error.message);const m=new Map();for(const x of s.data||[]){const k=String(x.driver_code||'').trim();if(!k)continue;const v=m.get(k)||{driver_code:k,driver_name:x.driver_name||'',invoices:0};v.invoices++;if(x.driver_name)v.driver_name=x.driver_name;m.set(k,v)}const out=[...m.values()].sort((a,b)=>b.invoices-a.invoices);return out[0]?{type:'invoice_volume',...out[0]}:b?{type:'assignment_volume',driver_code:b.code,driver_name:b.name,assignments:b.assignments}:null}
async function bestHelper(){return rankedPerson('helper')}
async function summarize(a:any){const d=clientFor(a.table,a.project);const h=await applyFilters(d.from(a.table).select('*',{head:true,count:'exact'}),a.filters);if(h.error)throw Error(h.error.message);const out:any={count:h.count||0};if(!a.column)return out;const vals:any[]=[];for(let from=0;from<50000;from+=1000){const r=await applyFilters(d.from(a.table).select(a.column),a.filters).range(from,from+999);if(r.error)throw Error(r.error.message);vals.push(...(r.data||[]).map((x:any)=>x[a.column]).filter((x:any)=>x!==null&&x!==undefined&&x!==''));if((r.data||[]).length<1000)break}const nums=vals.map(Number).filter(Number.isFinite);out.distinct_count=new Set(vals.map(String)).size;if(nums.length){out.sum=nums.reduce((a,b)=>a+b,0);out.avg=out.sum/nums.length;out.min=Math.min(...nums);out.max=Math.max(...nums)}return out}
async function providerCall(provider:string,key:string,model:string,messages:any[]){const base=provider==='groq'?'https://api.groq.com/openai/v1':provider==='openrouter'?'https://openrouter.ai/api/v1':'https://api.openai.com/v1';const r=await fetch(base+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({model:model||'gpt-4o-mini',messages,temperature:.15})});const b=await r.json();if(!r.ok)throw Error(b?.error?.message||'Provider HTTP '+r.status);return b?.choices?.[0]?.message?.content||''}
async function main(req:Request){if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const body=await req.json();const d=db('primary');const msg=String(body.message||'').trim();if(!msg)return json({reply:'Tell me what you want me to do.'});if(/\b(best|top)\b.*\b(driver|helper)\b|\b(driver|helper)\b.*\b(best|top)\b/i.test(msg)){try{
const role=/\bhelper\b/i.test(msg)?'helper':'driver';
const b=role==='helper'?await bestHelper():await bestDriver();
if(b){
let reply='';
if(b.type==='route_score') reply=`${role==='helper'?'Best helper':'Best driver'}: ${b.driver_name||b.name||b.driver_code||b.code} (${b.driver_code||b.code||'no code'}), average route score ${Number(b.avg_score).toFixed(2)} across ${b.assignments} assignment(s).`;
else if(b.type==='invoice_volume') reply=`${role==='helper'?'Best helper':'Best driver'} by recorded workload: ${b.driver_name||b.driver_code} (${b.driver_code||'no code'}), ${b.invoices} SAP invoice record(s).`;
else reply=`${role==='helper'?'Best helper':'Best driver'} by route-assignment workload: ${b.name||b.code} (${b.code}), ${b.assignments} assignment(s).`;
return json({reply,provider_used:'live-data',fallback_used:false,rag_available:true,pending_action:null})}}catch(e:any){return json({reply:'LOGI hit a live data error: '+(e?.message||'Unknown error'),provider_used:'live-data',fallback_used:false},400)}}
const cfg=(await d.from('ai_provider_config').select('provider,model,api_key,fallback_enabled,fallback_chain').eq('id','00000000-0000-0000-0000-000000000001').maybeSingle()).data||{};if(cfg.provider==='supabase-data')return json({reply:'I am connected to live DispatchOPS data. Ask me about drivers, invoices, fleet, GPS, Price Change, or Bulk Organizer.',provider_used:'supabase-data',fallback_used:false,rag_available:true});if(cfg.api_key){try{const prior=Array.isArray(body.history)?body.history.slice(-10).map((m:any)=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content||'').slice(0,6000)})):[];const reply=await providerCall(cfg.provider,cfg.api_key,cfg.model,[{role:'system',content:'You are LOGI, the DispatchOPS operations copilot. Answer the user directly and confidently. Never narrate your analysis plan, never say what you are going to check, never say "hold on", "please wait", or ask the user to wait. Do not expose internal reasoning or criteria unless the user explicitly asks how you calculated an answer. Give the useful answer first, then one short supporting detail if needed. Use the live DispatchOPS context available to you. public.drivers has no performance_rating; route_assignments contains driver_score and helper_score. driver_daily_divisions uses person_code, not driver_id. For rankings, use the actual route-assignment scores when populated; if a score is unavailable, clearly label workload/assignment volume as workload rather than quality. Keep responses concise and operational.'},...prior,{role:'user',content:msg}]);return json({reply,provider_used:cfg.provider,fallback_used:false,rag_available:true})}catch(e:any){return json({reply:'LOGI hit a live data/provider error: '+(e?.message||'Unknown error'),provider_used:cfg.provider,fallback_used:false},400)}}return json({reply:'I am connected to live DispatchOPS data, but no AI provider is configured for this request.',provider_used:'live-data',fallback_used:false,rag_available:true})}
Deno.serve(main);
