"""baseline: schema as of pre-verification-milestone V2 (all core Fleet/Route Planning/Dashboard/Experience/Analytics tables)

Revision ID: b1a0e2f5c001
Revises: 
Create Date: 2026-08-01 08:17:54.465508

This is the FIRST Alembic migration for this project. There was no prior
migration history - the app previously relied on Base.metadata.create_all()
+ core/auto_migrate.py's ad-hoc "ADD COLUMN IF NOT EXISTS" logic at
startup. That is being retired in favor of real, reviewable migrations
(see c2b1f3a6d002_add_area_groups_sheet_layout_salesman_division.py for the
schema changes introduced by the three most recent feature milestones -
Route Plan Sheet column layout persistence, Area Groups / Permitted Area
Groups / Driver Anchoring, and Salesman Categorization / Division
Detection - split out as its own migration so they're independently
reviewable/revertible from everything that existed before them).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b1a0e2f5c001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('fallback_enabled', sa.Boolean(), nullable=False),
    sa.Column('fallback_provider', sa.String(length=32), nullable=False),
    sa.Column('fallback_model', sa.String(length=128), nullable=False),
    sa.Column('fallback_key', sa.String(length=255), nullable=False),
    sa.Column('fallback_chain_json', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearance_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('light_bg_path', sa.String(length=500), nullable=False),
    sa.Column('dark_bg_path', sa.String(length=500), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('needs_driver', sa.String(length=16), nullable=False),
    sa.Column('needs_helper', sa.String(length=16), nullable=False),
    sa.Column('route_type', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'name', 'sector', name='uq_areas_code_name_division')
    )
    op.create_index(op.f('ix_areas_code'), 'areas', ['code'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('before_state_json', sa.Text(), nullable=False),
    sa.Column('after_state_json', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correlation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_no', sa.String(length=64), nullable=False),
    sa.Column('sap_customer_name', sa.String(length=255), nullable=False),
    sa.Column('matched_landmark_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.String(length=64), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_results_batch_id'), 'correlation_results', ['batch_id'], unique=False)
    op.create_table('customer_aliases',
    sa.Column('sap_name_normalized', sa.String(length=255), nullable=False),
    sa.Column('landmark_name_normalized', sa.String(length=255), nullable=False),
    sa.Column('sap_name_original', sa.String(length=255), nullable=False),
    sa.Column('landmark_name_original', sa.String(length=255), nullable=False),
    sa.Column('times_confirmed', sa.Integer(), nullable=False),
    sa.Column('best_confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sap_name_normalized', 'landmark_name_normalized')
    )
    op.create_table('dashboard_config_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_type', 'value', name='uq_dashboard_config_rule')
    )
    op.create_index(op.f('ix_dashboard_config_rules_rule_type'), 'dashboard_config_rules', ['rule_type'], unique=False)
    op.create_table('driver_aliases',
    sa.Column('sap_driver_normalized', sa.String(length=255), nullable=False),
    sa.Column('sap_driver_original', sa.String(length=255), nullable=False),
    sa.Column('landmark_driver_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('times_confirmed', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sap_driver_normalized')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('veh_type', sa.String(length=64), nullable=False),
    sa.Column('anchor_area', sa.String(length=255), nullable=False),
    sa.Column('health_card', sa.String(length=8), nullable=False),
    sa.Column('division', sa.String(length=16), nullable=False),
    sa.Column('preferred_helper', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_code'), 'drivers', ['code'], unique=True)
    op.create_table('experience_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_code', sa.String(length=32), nullable=False),
    sa.Column('person_name', sa.String(length=128), nullable=False),
    sa.Column('person_type', sa.String(length=16), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_history_person_code'), 'experience_history', ['person_code'], unique=False)
    op.create_table('feature_flags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('helpers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('anchor_area', sa.String(length=255), nullable=False),
    sa.Column('health_card', sa.String(length=8), nullable=False),
    sa.Column('division', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpers_code'), 'helpers', ['code'], unique=True)
    op.create_table('identity_review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('sap_code', sa.String(length=32), nullable=False),
    sa.Column('sap_name', sa.String(length=128), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('vehicle', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggested_code', sa.String(length=32), nullable=False),
    sa.Column('suggested_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_review_items_batch_id'), 'identity_review_items', ['batch_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('processed_units', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_seconds_remaining', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landmark_visit_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_raw', sa.String(length=64), nullable=False),
    sa.Column('vehicle_key', sa.String(length=32), nullable=False),
    sa.Column('arrival', sa.String(length=32), nullable=False),
    sa.Column('departure', sa.String(length=32), nullable=False),
    sa.Column('duration', sa.String(length=16), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('is_delivery', sa.Boolean(), nullable=False),
    sa.Column('is_passthrough', sa.Boolean(), nullable=False),
    sa.Column('is_depot', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmark_visit_facts_batch_id'), 'landmark_visit_facts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_landmark_visit_facts_vehicle_key'), 'landmark_visit_facts', ['vehicle_key'], unique=False)
    op.create_table('learned_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='uq_learned_value_category_value')
    )
    op.create_index(op.f('ix_learned_values_category'), 'learned_values', ['category'], unique=False)
    op.create_index(op.f('ix_learned_values_value'), 'learned_values', ['value'], unique=False)
    op.create_table('raw_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('row_json', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('imported_by', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_import_rows_batch_id'), 'raw_import_rows', ['batch_id'], unique=False)
    op.create_table('route_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_batch_id', sa.String(length=64), nullable=False),
    sa.Column('plan_role', sa.String(length=16), nullable=False),
    sa.Column('area_code', sa.String(length=32), nullable=False),
    sa.Column('area_name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('route_type', sa.String(length=32), nullable=False),
    sa.Column('driver_requirement', sa.String(length=16), nullable=False),
    sa.Column('helper_requirement', sa.String(length=16), nullable=False),
    sa.Column('driver_code', sa.String(length=32), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=False),
    sa.Column('helper_code', sa.String(length=32), nullable=False),
    sa.Column('helper_name', sa.String(length=128), nullable=False),
    sa.Column('vehicle_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('anchored_vehicle_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_assignment_reason', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('driver_score', sa.Integer(), nullable=False),
    sa.Column('driver_reason', sa.Text(), nullable=False),
    sa.Column('helper_score', sa.Integer(), nullable=False),
    sa.Column('helper_reason', sa.Text(), nullable=False),
    sa.Column('assignment_reason', sa.Text(), nullable=False),
    sa.Column('restrictions_considered', sa.Text(), nullable=False),
    sa.Column('is_vacation_replacement', sa.Boolean(), nullable=False),
    sa.Column('original_person_code', sa.String(length=32), nullable=False),
    sa.Column('original_person_name', sa.String(length=128), nullable=False),
    sa.Column('vacation_start_date', sa.String(length=10), nullable=False),
    sa.Column('vacation_end_date', sa.String(length=10), nullable=False),
    sa.Column('vacation_replacement_reason', sa.Text(), nullable=False),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_assignments_plan_batch_id'), 'route_assignments', ['plan_batch_id'], unique=False)
    op.create_index(op.f('ix_route_assignments_plan_role'), 'route_assignments', ['plan_role'], unique=False)
    op.create_table('sap_invoice_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_date', sa.String(length=10), nullable=False),
    sa.Column('dispatch_date', sa.String(length=10), nullable=False),
    sa.Column('dispatch_num', sa.String(length=64), nullable=False),
    sa.Column('invoice_no', sa.String(length=64), nullable=False),
    sa.Column('driver_code', sa.String(length=16), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=False),
    sa.Column('helper_code', sa.String(length=16), nullable=False),
    sa.Column('helper_name', sa.String(length=128), nullable=False),
    sa.Column('vehicle_num', sa.String(length=32), nullable=False),
    sa.Column('vehicle_key', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_name_source', sa.String(length=16), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('boxes', sa.Integer(), nullable=False),
    sa.Column('normal_boxes', sa.Integer(), nullable=False),
    sa.Column('freezer_boxes', sa.Integer(), nullable=False),
    sa.Column('not_supplied_reason', sa.String(length=255), nullable=False),
    sa.Column('division_desc', sa.String(length=128), nullable=False),
    sa.Column('txn_code', sa.String(length=32), nullable=False),
    sa.Column('facility_type', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=16), nullable=False),
    sa.Column('box_entry_time', sa.String(length=16), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_invoice_facts_batch_id'), 'sap_invoice_facts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_sap_invoice_facts_driver_code'), 'sap_invoice_facts', ['driver_code'], unique=False)
    op.create_index(op.f('ix_sap_invoice_facts_invoice_no'), 'sap_invoice_facts', ['invoice_no'], unique=False)
    op.create_index(op.f('ix_sap_invoice_facts_vehicle_key'), 'sap_invoice_facts', ['vehicle_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', 'VIEWER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vacations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_code', sa.String(length=32), nullable=False),
    sa.Column('person_name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacations_person_code'), 'vacations', ['person_code'], unique=False)
    op.create_table('vehicle_driver_manual_mappings',
    sa.Column('vehicle_key', sa.String(length=32), nullable=False),
    sa.Column('sap_driver', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_key')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('division', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_number'), 'vehicles', ['number'], unique=True)
    op.create_table('area_anchored_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'vehicle_id', name='uq_area_anchored_vehicle')
    )
    op.create_index(op.f('ix_area_anchored_vehicles_area_id'), 'area_anchored_vehicles', ['area_id'], unique=False)
    op.create_index(op.f('ix_area_anchored_vehicles_vehicle_id'), 'area_anchored_vehicles', ['vehicle_id'], unique=False)
    op.create_table('vehicle_permitted_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'area_id', name='uq_vehicle_permitted_area')
    )
    op.create_index(op.f('ix_vehicle_permitted_areas_area_id'), 'vehicle_permitted_areas', ['area_id'], unique=False)
    op.create_index(op.f('ix_vehicle_permitted_areas_vehicle_id'), 'vehicle_permitted_areas', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_permitted_areas_vehicle_id'), table_name='vehicle_permitted_areas')
    op.drop_index(op.f('ix_vehicle_permitted_areas_area_id'), table_name='vehicle_permitted_areas')
    op.drop_table('vehicle_permitted_areas')
    op.drop_index(op.f('ix_area_anchored_vehicles_vehicle_id'), table_name='area_anchored_vehicles')
    op.drop_index(op.f('ix_area_anchored_vehicles_area_id'), table_name='area_anchored_vehicles')
    op.drop_table('area_anchored_vehicles')
    op.drop_index(op.f('ix_vehicles_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('vehicle_driver_manual_mappings')
    op.drop_index(op.f('ix_vacations_person_code'), table_name='vacations')
    op.drop_table('vacations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sap_invoice_facts_vehicle_key'), table_name='sap_invoice_facts')
    op.drop_index(op.f('ix_sap_invoice_facts_invoice_no'), table_name='sap_invoice_facts')
    op.drop_index(op.f('ix_sap_invoice_facts_driver_code'), table_name='sap_invoice_facts')
    op.drop_index(op.f('ix_sap_invoice_facts_batch_id'), table_name='sap_invoice_facts')
    op.drop_table('sap_invoice_facts')
    op.drop_index(op.f('ix_route_assignments_plan_role'), table_name='route_assignments')
    op.drop_index(op.f('ix_route_assignments_plan_batch_id'), table_name='route_assignments')
    op.drop_table('route_assignments')
    op.drop_index(op.f('ix_raw_import_rows_batch_id'), table_name='raw_import_rows')
    op.drop_table('raw_import_rows')
    op.drop_index(op.f('ix_learned_values_value'), table_name='learned_values')
    op.drop_index(op.f('ix_learned_values_category'), table_name='learned_values')
    op.drop_table('learned_values')
    op.drop_index(op.f('ix_landmark_visit_facts_vehicle_key'), table_name='landmark_visit_facts')
    op.drop_index(op.f('ix_landmark_visit_facts_batch_id'), table_name='landmark_visit_facts')
    op.drop_table('landmark_visit_facts')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_identity_review_items_batch_id'), table_name='identity_review_items')
    op.drop_table('identity_review_items')
    op.drop_index(op.f('ix_helpers_code'), table_name='helpers')
    op.drop_table('helpers')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_experience_history_person_code'), table_name='experience_history')
    op.drop_table('experience_history')
    op.drop_index(op.f('ix_drivers_code'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('driver_aliases')
    op.drop_index(op.f('ix_dashboard_config_rules_rule_type'), table_name='dashboard_config_rules')
    op.drop_table('dashboard_config_rules')
    op.drop_table('customer_aliases')
    op.drop_index(op.f('ix_correlation_results_batch_id'), table_name='correlation_results')
    op.drop_table('correlation_results')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_areas_code'), table_name='areas')
    op.drop_table('areas')
    op.drop_table('appearance_config')
    op.drop_table('ai_provider_config')
    # ### end Alembic commands ###

