"""add version to control center config

Revision ID: fbddcc3bbc43
Revises: 9d13aa7e5aa7
Create Date: 2026-08-02 03:29:00.733698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbddcc3bbc43'
down_revision: Union[str, None] = '9d13aa7e5aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: added
    # server_default so this doesn't fail against a database that already
    # has a control_center_config row (e.g. from round -9's testing) -
    # NOT NULL with no default breaks on existing rows, caught by actually
    # running this against the same test database used in round -9 rather
    # than a fresh empty one. ###
    op.add_column('control_center_config', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('control_center_config', 'version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_center_config', 'version')
    # ### end Alembic commands ###
