import { useEffect, useRef, useState } from "react";
import {
  createLocationKnowledge, deleteLocationKnowledge, exportLocationKnowledge, importLocationKnowledgeFile,
  importLocationKnowledgeManagementFile, listAllLocationKnowledge, listLocationKnowledge, resetAllLocationKnowledge,
  updateLocationKnowledge, type LocationImportResult, type LocationKnowledgeRow,
} from "../services/locationKnowledge";
import { getPrimarySupabaseClient } from "../lib/supabase";

type Area = { id:string; code:string; name:string };
type Form = { customer_name:string; shipment_to:string; remarks:string; area_code:string; area_name:string; latest_invoice:string; first_seen_date:string; last_seen_date:string; seen_count:number; is_active:boolean; coordinates:string; t_nf1:string; t_nt1:string; t_nf2:string; t_nt2:string; t_ff:string; t_ft:string; t_sf:string; t_st:string; fri_off:boolean; sat_off:boolean; custom_days:string };
const emptyForm:Form={customer_name:"",shipment_to:"",remarks:"",area_code:"",area_name:"",latest_invoice:"",first_seen_date:"",last_seen_date:"",seen_count:1,is_active:true,coordinates:"",t_nf1:"",t_nt1:"",t_nf2:"",t_nt2:"",t_ff:"",t_ft:"",t_sf:"",t_st:"",fri_off:false,sat_off:false,custom_days:""};

export default function LocationKnowledge(){
  const sapFile=useRef<HTMLInputElement>(null), manageFile=useRef<HTMLInputElement>(null);
  const [rows,setRows]=useState<LocationKnowledgeRow[]>([]); const [areas,setAreas]=useState<Area[]>([]); const [search,setSearch]=useState("");
  const [busy,setBusy]=useState(false); const [result,setResult]=useState<LocationImportResult|null>(null); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [editing,setEditing]=useState<LocationKnowledgeRow|null>(null); const [form,setForm]=useState<Form>(emptyForm); const [showAdd,setShowAdd]=useState(false); const [showReset,setShowReset]=useState(false); const [password,setPassword]=useState("");
  async function refresh(q=search){try{setRows(await listLocationKnowledge(q));}catch(e){setError(e instanceof Error?e.message:String(e));}}
  async function loadAreas(){const {data,error}=await getPrimarySupabaseClient().from("areas").select("id,code,name").order("code");if(error)throw new Error(error.message);setAreas((data??[]) as Area[]);}
  useEffect(()=>{void Promise.all([refresh(""),loadAreas()]);},[]);
  function startEdit(r:LocationKnowledgeRow){setEditing(r);setForm({customer_name:r.customer_name,shipment_to:r.shipment_to,remarks:r.remarks,area_code:r.area_code,area_name:r.area_name,latest_invoice:r.latest_invoice||"",first_seen_date:r.first_seen_date||"",last_seen_date:r.last_seen_date||"",seen_count:r.seen_count,is_active:r.is_active!==false,coordinates:r.coordinates||"",t_nf1:r.t_nf1||"",t_nt1:r.t_nt1||"",t_nf2:r.t_nf2||"",t_nt2:r.t_nt2||"",t_ff:r.t_ff||"",t_ft:r.t_ft||"",t_sf:r.t_sf||"",t_st:r.t_st||"",fri_off:r.fri_off===true,sat_off:r.sat_off===true,custom_days:r.custom_days?JSON.stringify(r.custom_days):""});setShowAdd(true);}
  function startAdd(){setEditing(null);setForm(emptyForm);setShowAdd(true);}
  async function save(){setBusy(true);setError("");setMessage("");try{const payload={...form,custom_days:(()=>{try{return form.custom_days?JSON.parse(form.custom_days):[];}catch{throw new Error("Custom Days must be valid JSON.");}})()}; if(editing?.id)await updateLocationKnowledge(editing.id,payload);else await createLocationKnowledge(payload);setShowAdd(false);setMessage(editing?"Location record updated successfully.":"Customer location added successfully.");await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function uploadSap(){const file=sapFile.current?.files?.[0];if(!file)return;setBusy(true);setError("");setMessage("");setResult(null);try{setResult(await importLocationKnowledgeFile(file));await refresh("");if(sapFile.current)sapFile.current.value="";}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function uploadManagement(){const file=manageFile.current?.files?.[0];if(!file)return;setBusy(true);setError("");setMessage("");try{const r=await importLocationKnowledgeManagementFile(file);setMessage(`Excel management import complete: ${r.created} created, ${r.updated} updated.`);await refresh("");if(manageFile.current)manageFile.current.value="";}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function remove(r:LocationKnowledgeRow){if(!r.id||!confirm(`Delete this customer location pattern for ${r.customer_name}?`))return;try{await deleteLocationKnowledge(r.id);await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}}
  async function reset(){if(password!=="0000"){setError("Incorrect reset password.");return;}setBusy(true);setError("");try{const n=await resetAllLocationKnowledge();setShowReset(false);setPassword("");setMessage(`${n} location knowledge records were permanently erased.`);await refresh("");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  function areaChanged(code:string){const a=areas.find(x=>x.code===code);setForm(f=>({...f,area_code:code,area_name:a?.name||""}));}
  return <div className="page">
    <h2>Invoice Location Knowledge</h2>
    <p style={{color:"var(--muted)",fontSize:13,marginTop:-8}}>Full management of customer location knowledge. You can edit every field, correct Area Codes, add customers manually, export Excel backups, and merge edited Excel files back into DispatchOPS.</p>
    <div className="glass-card" style={{marginBottom:18}}>
      <strong>Location Knowledge Management</strong>
      <div style={{color:"var(--muted)",fontSize:12,marginTop:5}}>Area Code is selected from Fleet Data → Areas, so the Area Name always stays synchronized. SAP learning remains non-destructive and does not keep the original workbook.</div>
      <div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",marginTop:14}}>
        <button className="btn" onClick={startAdd}>＋ Add Customer Manually</button>
        <button className="btn" onClick={()=>manageFile.current?.click()} disabled={busy}>⬆ Upload Management Excel</button>
        <button className="btn" onClick={async()=>{setBusy(true);try{exportLocationKnowledge(await listAllLocationKnowledge());setMessage("Excel export created successfully.");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}} disabled={busy}>⬇ Download Excel</button>
        <input ref={manageFile} type="file" accept=".xlsx,.xls,.csv" hidden onChange={()=>void uploadManagement()}/>
        <span style={{width:1,height:26,background:"var(--border)"}} />
        <input ref={sapFile} type="file" accept=".xlsx,.xls,.csv" disabled={busy}/><button className="btn" disabled={busy} onClick={()=>void uploadSap()}>{busy?"Working…":"Learn From SAP Excel"}</button>
        <button className="btn" style={{background:"var(--red)"}} onClick={()=>setShowReset(true)}>Reset / Erase All</button>
      </div>
      {result&&<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><span className="badge ok">{result.savedPatterns} patterns saved/updated</span><span className="badge">{result.sourceRows} source rows</span><span className="badge">{result.excludedNotSupply} Not Supply excluded</span><span className="badge">{result.unresolvedArea} unresolved areas skipped</span></div>}
      {message&&<div style={{color:"var(--green,#4ade80)",marginTop:10,fontSize:12}}>{message}</div>}{error&&<div style={{color:"var(--red)",marginTop:10,fontSize:12}}>{error}</div>}
    </div>
    <div className="glass-card table-scroll">
      <div style={{display:"flex",gap:10,alignItems:"center",marginBottom:10}}><strong style={{flex:1}}>Customer Location Records ({rows.length})</strong><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void refresh();}} placeholder="Customer, shipment, remarks or area…" style={{minWidth:320}}/><button className="btn" onClick={()=>void refresh()}>Search</button></div>
      <table className="data-table"><thead><tr><th>Customer</th><th>Shipment To</th><th>Remarks / Instructions</th><th>Area Code</th><th>Area Name</th><th>Seen</th><th>Latest Invoice</th><th>First Seen</th><th>Last Seen</th><th>Coordinates</th><th>Normal</th><th>Friday</th><th>Saturday</th><th>Active</th><th>Actions</th></tr></thead>
      <tbody>{rows.length===0&&<tr><td colSpan={15} style={{textAlign:"center",padding:20,color:"var(--muted)"}}>No location knowledge yet.</td></tr>}{rows.map(r=><tr key={r.id}><td><strong>{r.customer_name}</strong></td><td style={{maxWidth:260,whiteSpace:"normal"}}>{r.shipment_to||"—"}</td><td style={{maxWidth:280,whiteSpace:"normal"}}>{r.remarks||"—"}</td><td><span className="badge ok">{r.area_code}</span></td><td>{r.area_name}</td><td>{r.seen_count}</td><td>{r.latest_invoice||"—"}</td><td>{r.first_seen_date||"—"}</td><td>{r.last_seen_date||"—"}</td><td>{r.coordinates||"—"}</td><td>{r.t_nf1||r.t_nt1?`${r.t_nf1||"—"}–${r.t_nt1||"—"}`:"—"}</td><td>{r.fri_off?"CLOSED":(r.t_ff||r.t_ft?`${r.t_ff||"—"}–${r.t_ft||"—"}`:"—")}</td><td>{r.sat_off?"CLOSED":(r.t_sf||r.t_st?`${r.t_sf||"—"}–${r.t_st||"—"}`:"—")}</td><td>{r.is_active===false?"NO":"YES"}</td><td style={{whiteSpace:"nowrap"}}><button className="btn" onClick={()=>startEdit(r)}>Edit</button> <button className="btn" style={{background:"var(--red)"}} onClick={()=>void remove(r)}>Delete</button></td></tr>)}</tbody></table>
    </div>
    {showAdd&&<div className="modal-overlay" style={{position:"fixed",inset:0,zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.72)",padding:16}}><div className="glass-card" style={{width:"min(900px,96vw)",maxHeight:"90vh",overflow:"auto"}}><h3>{editing?"Edit Customer Location":"Add Customer Location"}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginTop:12}}>
      <label>Customer<input value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></label>
      <label>Area Code<select value={form.area_code} onChange={e=>areaChanged(e.target.value)}><option value="">Select Area Code…</option>{areas.map(a=><option key={a.id} value={a.code}>{a.code} — {a.name}</option>)}</select></label>
      <label style={{gridColumn:"1/-1"}}>Shipment To / Address<textarea value={form.shipment_to} onChange={e=>setForm({...form,shipment_to:e.target.value})}/></label>
      <label style={{gridColumn:"1/-1"}}>Remarks / Instructions<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label>
      <label>Area Name<input value={form.area_name} readOnly/></label><label>Latest Invoice<input value={form.latest_invoice} onChange={e=>setForm({...form,latest_invoice:e.target.value})}/></label>
      <label>First Seen Date<input type="date" value={form.first_seen_date} onChange={e=>setForm({...form,first_seen_date:e.target.value})}/></label><label>Last Seen Date<input type="date" value={form.last_seen_date} onChange={e=>setForm({...form,last_seen_date:e.target.value})}/></label>
      <label>Seen Count<input type="number" min={1} value={form.seen_count} onChange={e=>setForm({...form,seen_count:Number(e.target.value)})}/></label><label>Coordinates / GPS<input value={form.coordinates} onChange={e=>setForm({...form,coordinates:e.target.value})} placeholder="25.12345, 55.12345"/></label>
      <label>Normal Start<input type="time" value={form.t_nf1} onChange={e=>setForm({...form,t_nf1:e.target.value})}/></label><label>Normal End<input type="time" value={form.t_nt1} onChange={e=>setForm({...form,t_nt1:e.target.value})}/></label>
      <label>Normal 2 Start<input type="time" value={form.t_nf2} onChange={e=>setForm({...form,t_nf2:e.target.value})}/></label><label>Normal 2 End<input type="time" value={form.t_nt2} onChange={e=>setForm({...form,t_nt2:e.target.value})}/></label>
      <label>Friday Start<input type="time" value={form.t_ff} onChange={e=>setForm({...form,t_ff:e.target.value})}/></label><label>Friday End<input type="time" value={form.t_ft} onChange={e=>setForm({...form,t_ft:e.target.value})}/></label>
      <label>Saturday Start<input type="time" value={form.t_sf} onChange={e=>setForm({...form,t_sf:e.target.value})}/></label><label>Saturday End<input type="time" value={form.t_st} onChange={e=>setForm({...form,t_st:e.target.value})}/></label>
      <label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={form.fri_off} onChange={e=>setForm({...form,fri_off:e.target.checked})}/> Friday Closed</label><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={form.sat_off} onChange={e=>setForm({...form,sat_off:e.target.checked})}/> Saturday Closed</label>
      <label style={{gridColumn:"1/-1"}}>Custom Days JSON<input value={form.custom_days} onChange={e=>setForm({...form,custom_days:e.target.value})} placeholder='[{"day":"SUN","f":"09:00","t":"14:00"}]'/></label><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label>
    </div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button className="btn" onClick={()=>setShowAdd(false)}>Cancel</button><button className="btn" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save"}</button></div></div></div>}
    {showReset&&<div className="modal-overlay" style={{position:"fixed",inset:0,zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.72)",padding:16}}><div className="glass-card" style={{width:"min(460px,94vw)"}}><h3 style={{color:"var(--red)"}}>Erase All Location Knowledge</h3><p style={{color:"var(--muted)",fontSize:13}}>This permanently deletes every customer/location knowledge record from DispatchOPS. This does not delete Fleet Areas or SAP source files.</p><input type="password" autoFocus placeholder="Enter reset password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void reset();}}/><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:14}}><button className="btn" onClick={()=>{setShowReset(false);setPassword("")}}>Cancel</button><button className="btn" style={{background:"var(--red)"}} disabled={busy} onClick={()=>void reset()}>Erase All Data</button></div></div></div>}
  </div>;
}
