-- DispatchOPS frontend compatibility layer.
-- The live database originally had canonical renamed columns while the migrated
-- frontend still references the legacy field names. This migration preserves
-- both contracts so every screen can use the same shared Supabase database.
alter table public.drivers add column if not exists code text;
alter table public.drivers add column if not exists name text;
alter table public.helpers add column if not exists code text;
alter table public.helpers add column if not exists name text;
alter table public.areas add column if not exists code text;
alter table public.areas add column if not exists name text;
alter table public.areas add column if not exists sector text not null default 'Pharma';
alter table public.areas add column if not exists needs_driver text not null default 'Mandatory';
alter table public.areas add column if not exists needs_helper text not null default 'Optional';
alter table public.areas add column if not exists route_type text not null default 'Main Route';
alter table public.areas add column if not exists vehicle_type text not null default 'Van';
alter table public.vehicles add column if not exists number text;
alter table public.vehicles add column if not exists type text not null default 'VAN';
alter table public.import_batches add column if not exists original_filename text not null default '';
alter table public.import_batches add column if not exists imported_by text not null default '';
alter table public.import_batches add column if not exists imported_by_device text not null default '';
alter table public.import_batches add column if not exists imported_at timestamptz not null default now();
alter table public.import_batches add column if not exists success_count integer not null default 0;
alter table public.import_batches add column if not exists failed_count integer not null default 0;
alter table public.import_batches add column if not exists validation_errors jsonb not null default '[]'::jsonb;
alter table public.sap_invoice_facts add column if not exists batch_id uuid;
alter table public.sap_invoice_facts add column if not exists invoice_no text;
alter table public.sap_invoice_facts add column if not exists dispatch_num text not null default '';
alter table public.sap_invoice_facts add column if not exists helper_code text not null default '';
alter table public.sap_invoice_facts add column if not exists helper_name text not null default '';
alter table public.sap_invoice_facts add column if not exists vehicle_num text not null default '';
alter table public.sap_invoice_facts add column if not exists vehicle_key text not null default '';
alter table public.sap_invoice_facts add column if not exists customer_name_source text not null default '';
alter table public.sap_invoice_facts add column if not exists remarks text not null default '';
alter table public.sap_invoice_facts add column if not exists address text not null default '';
alter table public.sap_invoice_facts add column if not exists boxes integer not null default 0;
alter table public.sap_invoice_facts add column if not exists normal_boxes integer not null default 0;
alter table public.sap_invoice_facts add column if not exists freezer_boxes integer not null default 0;
alter table public.sap_invoice_facts add column if not exists not_supplied_reason text not null default '';
alter table public.sap_invoice_facts add column if not exists division_desc text not null default '';
alter table public.sap_invoice_facts add column if not exists txn_code text not null default '';
alter table public.sap_invoice_facts add column if not exists facility_type text not null default '';
alter table public.sap_invoice_facts add column if not exists vehicle_type text not null default '';
alter table public.sap_invoice_facts add column if not exists salesman text not null default '';
alter table public.sap_invoice_facts add column if not exists box_entry_time text not null default '';
alter table public.sap_invoice_facts add column if not exists source_file text not null default '';
alter table public.sap_invoice_facts add column if not exists imported_at timestamptz not null default now();
alter table public.sap_invoice_facts add column if not exists is_order integer not null default 1;
alter table public.sap_invoice_facts add column if not exists is_resupply boolean not null default false;
alter table public.sap_invoice_facts add column if not exists excluded boolean not null default false;
alter table public.sap_invoice_facts add column if not exists raw_data jsonb;
alter table public.landmark_visit_facts add column if not exists batch_id uuid;
alter table public.landmark_visit_facts add column if not exists vehicle_raw text not null default '';
alter table public.landmark_visit_facts add column if not exists vehicle_key text not null default '';
alter table public.landmark_visit_facts add column if not exists arrival text not null default '';
alter table public.landmark_visit_facts add column if not exists departure text not null default '';
alter table public.landmark_visit_facts add column if not exists duration text not null default '';
alter table public.landmark_visit_facts add column if not exists minutes integer not null default 0;
alter table public.landmark_visit_facts add column if not exists is_delivery boolean not null default false;
alter table public.landmark_visit_facts add column if not exists is_passthrough boolean not null default false;
alter table public.landmark_visit_facts add column if not exists is_depot boolean not null default false;
alter table public.landmark_visit_facts add column if not exists source_file text not null default '';
alter table public.landmark_visit_facts add column if not exists imported_at timestamptz not null default now();
alter table public.vehicle_driver_manual_mappings add column if not exists vehicle_key text;
alter table public.vehicle_driver_manual_mappings add column if not exists sap_driver text;
alter table public.vehicle_driver_manual_mappings add column if not exists updated_by text not null default '';
alter table public.customer_aliases add column if not exists sap_name_normalized text;
alter table public.customer_aliases add column if not exists landmark_name_normalized text;
alter table public.customer_aliases add column if not exists sap_name_original text not null default '';
alter table public.customer_aliases add column if not exists landmark_name_original text not null default '';
alter table public.customer_aliases add column if not exists times_confirmed integer not null default 1;
alter table public.customer_aliases add column if not exists best_confidence double precision not null default 0;
alter table public.customer_aliases add column if not exists first_seen timestamptz not null default now();
alter table public.customer_aliases add column if not exists last_seen timestamptz not null default now();
alter table public.driver_daily_divisions add column if not exists person_code text;
alter table public.driver_daily_divisions add column if not exists person_name text;
alter table public.driver_daily_divisions add column if not exists consumer_invoices integer not null default 0;
alter table public.driver_daily_divisions add column if not exists pharma_invoices integer not null default 0;
alter table public.ai_provider_config add column if not exists api_key text not null default '';
alter table public.ai_provider_config add column if not exists fallback_enabled boolean not null default false;
alter table public.ai_provider_config add column if not exists fallback_provider text not null default 'ollama';
alter table public.ai_provider_config add column if not exists fallback_model text not null default '';
alter table public.ai_provider_config add column if not exists fallback_key text not null default '';
alter table public.ai_provider_config add column if not exists fallback_chain jsonb not null default '[]'::jsonb;
alter table public.ai_provider_config add column if not exists updated_by text not null default '';
alter table public.control_center_config add column if not exists version integer not null default 1;
alter table public.control_center_config add column if not exists updated_by text not null default '';
alter table public.route_sheet_layout add column if not exists column_order jsonb not null default '[]'::jsonb;
alter table public.route_sheet_layout add column if not exists hidden_columns jsonb not null default '[]'::jsonb;
alter table public.route_sheet_layout add column if not exists column_widths jsonb not null default '{}'::jsonb;
alter table public.route_sheet_layout add column if not exists updated_by text not null default '';
alter table public.audit_log add column if not exists entity_key text not null default '';
alter table public.audit_log add column if not exists actor text not null default '';
alter table public.audit_log add column if not exists before_state jsonb not null default '{}'::jsonb;
alter table public.audit_log add column if not exists after_state jsonb not null default '{}'::jsonb;
alter table public.audit_log add column if not exists success boolean not null default true;
alter table public.audit_log add column if not exists error_message text not null default '';
alter table public.audit_log add column if not exists duration_ms integer not null default 0;
alter table public.audit_log add column if not exists undone boolean not null default false;
alter table public.audit_log add column if not exists "timestamp" timestamptz not null default now();
alter table public.app_backups add column if not exists label text not null default '';
alter table public.app_backups add column if not exists created_by text not null default '';
alter table public.app_backups add column if not exists row_count integer not null default 0;
alter table public.app_backups add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.app_backups add column if not exists backup_name text;
alter table public.learned_values add column if not exists key text;
alter table public.learned_values add column if not exists category text not null default '';
alter table public.jobs add column if not exists job_type text not null default '';
alter table public.jobs add column if not exists progress integer not null default 0;
alter table public.jobs add column if not exists message text not null default '';
alter table public.jobs add column if not exists error text;
alter table public.jobs add column if not exists created_by text not null default '';
alter table public.jobs add column if not exists updated_at timestamptz not null default now();
create table if not exists public.vacations (id uuid primary key default gen_random_uuid(), person_code text not null default '', person_name text not null default '', person_type text not null default 'Driver', start_date date not null, end_date date not null);
create table if not exists public.experience_history (id uuid primary key default gen_random_uuid(), person_code text not null default '', person_name text not null default '', person_type text not null default 'Driver', area text not null default '', sector text not null default 'Pharma', date date not null default current_date, end_date date, vehicle_number text not null default '');
create table if not exists public.area_groups (id uuid primary key default gen_random_uuid(), name text not null unique);
create table if not exists public.area_group_members (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.area_groups(id) on delete cascade, area_id uuid not null references public.areas(id) on delete cascade, sort_order integer not null default 0);
create table if not exists public.vehicle_permitted_area_groups (id uuid primary key default gen_random_uuid(), vehicle_id uuid not null references public.vehicles(id) on delete cascade, group_id uuid not null references public.area_groups(id) on delete cascade);
create table if not exists public.driver_anchored_areas (id uuid primary key default gen_random_uuid(), driver_id uuid not null references public.drivers(id) on delete cascade, area_id uuid not null references public.areas(id) on delete cascade, sort_order integer not null default 0);
create table if not exists public.driver_anchored_area_groups (id uuid primary key default gen_random_uuid(), driver_id uuid not null references public.drivers(id) on delete cascade, group_id uuid not null references public.area_groups(id) on delete cascade, sort_order integer not null default 0);
create table if not exists public.vehicle_permitted_areas (id uuid primary key default gen_random_uuid(), vehicle_id uuid not null references public.vehicles(id) on delete cascade, area_id uuid not null references public.areas(id) on delete cascade);
create table if not exists public.area_anchored_vehicles (id uuid primary key default gen_random_uuid(), area_id uuid not null references public.areas(id) on delete cascade, vehicle_id uuid not null references public.vehicles(id) on delete cascade);
create table if not exists public.route_assignments (id uuid primary key default gen_random_uuid(), plan_batch_id text not null default '', plan_role text not null default 'driver', area_code text not null default '', area_name text not null default '', sector text not null default 'Pharma', route_type text not null default 'Main Route', driver_requirement text not null default 'Mandatory', helper_requirement text not null default 'Optional', driver_code text not null default '', driver_name text not null default '', helper_code text not null default '', helper_name text not null default '', vehicle_number text not null default '', vehicle_type text not null default '', anchored_vehicle_number text not null default '', vehicle_assignment_reason text not null default '', start_date date not null default current_date, end_date date not null default current_date, driver_score integer not null default 0, driver_reason text not null default '', helper_score integer not null default 0, helper_reason text not null default '', assignment_reason text not null default '', restrictions_considered text not null default '', is_vacation_replacement boolean not null default false, original_person_code text not null default '', original_person_name text not null default '', vacation_start_date date, vacation_end_date date, vacation_replacement_reason text not null default '', is_manually_edited boolean not null default false, status text not null default 'Pending', sort_order integer not null default 0, created_by text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.raw_import_rows (id uuid primary key default gen_random_uuid(), source_type text not null default '', batch_id uuid, source_filename text not null default '', row_index integer not null default 0, row_json jsonb not null default '{}'::jsonb, imported_at timestamptz not null default now(), imported_by text not null default '', label text not null default '');
create unique index if not exists ux_vehicle_driver_manual_mappings_vehicle_key on public.vehicle_driver_manual_mappings(vehicle_key);
